services:
  vote_db:
    image: mariadb:latest
    container_name: vote_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - vote-data:/var/lib/mysql
    networks:
      - vote-network

  vote_redis:
    image: redis:latest
    container_name: vote_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - vote-network

  vote_spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vote_spring
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - vote-network

volumes:
  vote-data:

networks:
  vote-network:
    driver: bridge
