version: "3.8"

services:
  vote_db:
    image: mariadb:latest
    container_name: vote_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${VOTE_DATA_VOLUME}:/var/lib/mysql
    networks:
      - ${NETWORK_NAME}

  vote_redis:
    image: redis:latest
    container_name: vote_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ${NETWORK_NAME}

  vote_spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vote_spring
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - .env
    networks:
      - ${NETWORK_NAME}

volumes:
  ${VOTE_DATA_VOLUME}:

networks:
  ${NETWORK_NAME}:
    driver: bridge
