server:
  port: 443
  ssl:
    keystore: /etc/letsencrtypt/live/www.caufencing.com/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    enabled: true

spring:
  application:
    name: vote
  profiles:
#    active: local
    active: release
#    active: test
