name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 자바 다운로드
      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'  # Amazon Corretto 배포판을 사용
          java-package: jdk
          check-latest: false
      
      # 2. keystore.p12 파일 복원
      - name: Restore keystore.p12 from GitHub Secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ./keystore.p12

      # 3. application.properties 파일 복원
      - name: Restore application.properties from GitHub Secrets
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties

      # 4. Docker compose 파일 복원
      - name: Restore docker-compose.yml from GitHub Secrets
        run: |
          echo "${{ secrets.DOCKER_COMPOSE }}" > ./src/main/docker-compose.yml
      
      # 3. Gradle 실행 파일에 권한 부여
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 비밀번호 또는 액세스 토큰


      # 6. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ksngh/cau_vote:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # 도커 컴포즈 할 수 있는 환경으로 바꿔두기
    steps:
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            echo "${{ secrets.DOCKER_COMPOSE }}" > /home/ubuntu/docker-compose.yml
            echo "${{ secrets.APPLICATION_PROPERTIES }}" > /home/ubuntu/application.properties
            cd /home/ubuntu
            sudo docker pull ksngh/cau_vote:latest
            sudo docker stop cau_vote || true
            sudo docker rm cau_vote || true
            sudo docker-compose --project-name cau_vote up
