name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Java 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ksngh/cau_vote:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ksngh/cau_vote:latest
            docker stop cau_vote || true
            docker rm cau_vote || true
            docker run -d -p 443:443 --name cau_vote ksngh/cau_vote:latest
