name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    # 도커 컴포즈 할 수 있는 환경으로 바꿔두기
    # echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./keystore.p12
    steps:
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker stop vote_spring || true
            sudo docker rm vote_spring || true
            cd /home/ubuntu/cau_vote
            git pull origin main || true
            echo "${{ secrets.ENV }}" > ./.env
            echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./src/main/resources/keystore.p12
            sudo docker-compose up -d
            exit 0
